### ISSUE TITLE
problem with  example in manual

### ISSUE THREAD

**Issue by parsifal9** [camilo-v/jasper#3]
Hi Camilo-v,

I am have trouble getting the example described in the manual working.
Am I running the command correctly?  Am I missing some step?

```
git clone https://github.com/camilo-v/jasper.git
cd jasper
wget https://www.microbiomemaps.org/s/Example-Abundances.zip
unzip  Example-Abundances.zip 
python3 jasper.py --profile Examples/Abundances-Taxonomic.txt --type matrix  --order taxonomic --min_num_levels 10 --output OUTPUT

───────────────────────────────────────────────────────────────────────────────
   _____ _______ _______  _____  _______  ______        Version B1.2023021075
     |   |_____| |______ |_____] |______ |_____/                Jasper
   __|   |     | ______| |       |______ |    \_         ______(BETA)_______
                                                                              
   https://github.com/camilo-v/jasper                               
 ───────────────────────────────────────────────────────────────────────────────
[21-Dec-2023 10:08:38]
[21-Dec-2023 10:08:38] Starting Visualization...
[21-Dec-2023 10:08:38] Ordering Scheme: TAXONOMIC
[21-Dec-2023 10:08:38] Preparing Output Directory...
[21-Dec-2023 10:08:38]
[21-Dec-2023 10:08:38] Analyzing Profiles...
[21-Dec-2023 10:08:38] Type: MATRIX
[21-Dec-2023 10:08:38] Loading...
[21-Dec-2023 10:08:38] Number of Microbes: 3
[21-Dec-2023 10:08:38] Number of Samples: 44,047
[21-Dec-2023 10:08:38]
[21-Dec-2023 10:08:38] Creating Hilbert Images...
[21-Dec-2023 10:08:38]  - 1 Processing 546270 (1494.0448) Traceback (most recent call last):
  File "/home/dun280/Downloads/jasper/jasper.py", line 343, in <module>
    main(sys.argv[1:])
  File "/home/dun280/Downloads/jasper/jasper.py", line 293, in main
    r_subprocess = sp.Popen(r_hilbert_cmd, stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE)
  File "/home/dun280/local/anaconda3/envs/qiskit/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/dun280/local/anaconda3/envs/qiskit/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/dun280/Downloads/jasper/R_scripts/hilbert.R'

```

```
> python --version
Python 3.9.5
>  R 
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
>  uname -a
Linux 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nitinShukla1912** [comment]
@parsifal9  Did You find any solution to the above error?

**Comment by parsifal9** [comment]
> @parsifal9 Did You find any solution to the above error?

I did not. 
In addition, I think the command Rscript is missing from jasper.py i.e I think
```
r_hilbert_cmd_str = r_script_path + '/hilbert.R --work_dir \"' + r_work_dir + '\"' + \
```
should be 
```
 r_hilbert_cmd_str = 'Rscript ' + r_script_path + '/hilbert.R --work_dir \"' + r_work_dir + '\"' + \
```

This convinced me that the released version is not working and I stopped playing with it. We can only hope that a working version is coming.

**Comment by nitinShukla1912** [comment]
@parsifal9 There were few changes in the script as some of the libraries were requested but not loaded, 

`python3 jasper.py --profile Examples/Abundances-Taxonomic.txt --type matrix  --order taxonomic --min_num_levels 10 --output OUTPUT4 --verbose`

![jasper](https://github.com/camilo-v/jasper/assets/96987153/6f5a5a86-a168-4a95-af1e-06ed1e142341)


Somehow I was able to get the images (.png) but they were all empty.
